### PR TITLE
Fix hyperlink in Developers/Development_Setup.rst and Users/Tutorials.rst #247

### PR DESCRIPTION
**Pull request by arjunsinghy96**
Hyperlink "virtualenv setup" in Developers/Development_Setup.rst refer to MAC Hints virtual environment setup and "supported languages" in Users/Tutorials.rst refer to supported languages doc page on github.

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
hey, it seems that you have not setup commit authorship correctly (probably used another email or such) so please do so :)

**Comment by Adrianzatreanu** [comment]
also, your commit messages are not following our guidelines, could you please take a look on coala.io/commit and edit them? Thanks!

**Comment by arjunsinghy96** [comment]
@Adrianzatreanu I would look into it. Thanks for the suggestions. :smile:

**Comment by arjunsinghy96** [comment]
@Adrianzatreanu @sils  I have done the required amendments . Please inform if any other change has to be done.

**Comment by sils** [comment]
ack https://github.com/coala/documentation/pull/276/commits/5b2206b8299bae0f28fd7cfc40d476debcc7712d

**Comment by sils** [comment]
can you make a rebase?

**Comment by arjunsinghy96** [comment]
Sorry @sils . I think I do not completely understand what you meant by to make a rebase. Could you please explain a little. I am sure I can do that once it is clear what is to be done.

**Comment by sils** [comment]
That is indeed a rather frequent question and we do have a template answer for that already even ;)

---

Hi,

it looks like your PR is out of date and needs a rebase. [This page](http://coala.io/git) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

(Be sure to use coala-bears on the coala-bears repository :))

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix it up for you - just tell us :).

Ping us on [our gitter channel](https://coala.io/chat) if you need help!

**Comment by arjunsinghy96** [comment]
@sils Docs were helpful
I did a rebase and now am 1 commit ahead of coala:master

**Comment by arjunsinghy96** [comment]
Now I think I also understand the concept of rebase

**Comment by sils** [comment]
reack https://github.com/coala/documentation/pull/276/commits/a64928edeeff941ec9a5476ee0707e120f4cdede

**Comment by sils** [comment]
@rultor merge

**Comment by sils** [comment]
Hey, this is your first contribution, right? Congrats and welcome to the coalaians! :)

You can help us a lot by filling out <http://coala.io/newform>!

Rultor will now automatically release your changes as a prerelease so users can experience the goodness of your changes right now.

See also https://github.com/coala-analyzer/coala/wiki/coala-Steam-Offer btw.

We would really appreciate it if you could help us with

- some code reviews for other newcomers
- fixing at least a difficulty/low issue

We're all volunteers and we're currently struggling to keep this up. Helping all those newcomers is a lot of work and we do need your help so we can continue this for others!

**Pull request merged**
