### PR TITLE
MAC_Hints.rst: Documentation Error

### PR DESCRIPTION
**Pull request by naveentata**
Closes: https://github.com/coala/documentation/issues/383

### CODE REVIEW

**Comment by aptrishu** [comment]
Documentation Error -> Fix the Documentation error..

**Comment by aptrishu** [comment]
Closes -> Fixes
and there should be  no colon after Fixes/closes.

**Comment by supergr35** [comment]
ack 91a29f1

**Comment by sims1253** [comment]
unack 91a29f133b0b7a9d7db16cc1208aa0b16afcb8ba

**Comment by sims1253** [comment]
can you change the fixes in the commit message? looks like you only changed it in the pr description.
Just `git commit --amend`, change Fixes to Closes and `git push -f` to force a push

**Comment by naveentata** [comment]
@sims1253 Is this alright now?

**Comment by sims1253** [comment]
ack 4ecf6c80d08182a01c93f84d33deafd7624c0aa1

**Comment by sims1253** [comment]
@rultor merge

**Comment by sims1253** [comment]
you probably have to rebase.

**Comment by gkrishnan724** [comment]
ack  	6bad575

**Comment by gkrishnan724** [comment]
ack  	6bad575

**Comment by sils** [comment]
ack https://github.com/coala/documentation/pull/401/commits/6bad57536f3c54bd7a080ce68d52b6b526eb4ade

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
