### PR TITLE
Globe_Patterns.rst: looses->loses\nCloses: https://github.com/coala/d…

### PR DESCRIPTION
**Pull request by DumAdrian**
…ocumentation/issues/118

### CODE REVIEW

**Comment by tulphoon** [comment]
ack 03a8110

**Comment by tulphoon** [comment]
unack 83a8110

**Comment by tulphoon** [comment]
unack 03a8110

**Comment by tulphoon** [comment]
edit the commit shortlog to be `Globe_Patterns.rst: Change "looses" to "loses"`

**Comment by sils** [comment]
IMO both variants are acceptable. @tulphoon I like how strict you are, it seems that @DumAdrian has read the docs quite well and made a decent shortlog. IMO it suffices, are you fine with us merging it as is?

**Comment by tulphoon** [comment]
ack 03a8110

**Comment by sils** [comment]
@rultor merge

**Comment by sils** [comment]
Thanks so much for your help @tulphoon !

**Pull request merged**
