### PR TITLE
coafile: Provide config settings link in end

### LINKED ISSUE #446: Writing a coala Configuration File (coafile and coarc) doesnt show what can actually be used within the coafile
[Writing a coala Configuration File (coafile and coarc)](http://docs.coala.io/en/latest/Users/coafile.html#) describes only the structure of the coafile. Which is confusing, because the title suggest, that the page will teach you how to write the coafile.

So when the user finished read the above page, the user knows how to structure the file, but doesnt know which setting he can actually use, etc.

A link to http://docs.coala.io/en/latest/Users/Tutorial.html in the beginning and the end could be a quick fix

### PR DESCRIPTION
**Pull request by seven-binoche**
This tells the user about configuration settings that can be
changed after learning the structure of coafiles.

Closes #446

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Arsfiqball** [comment]
Please squash your commit @seven-binoche

**Comment by IpshitaC** [comment]
ack a0b94b85775d35cc377ddd7f58648d7d92000b1f

**Comment by Nosferatul** [comment]
@seven-binoche please rebase and LGTM

**Comment by sils** [comment]
reack https://github.com/coala/documentation/pull/451/commits/d22d9db0416c18043e85e85d4357d413ebc3b5cb

(Rebased it for you to get this merged)

**Comment by sils** [comment]
ack d22d9db

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
