### PR TITLE
Proposed file change

### PR DESCRIPTION
**Pull request by achetan40**
This resolves issue #148
Changed "It is obvious we need good commits." to "We need good commits".

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
Hi,

it seems that your commit message doesn't contain enough information. Don't worry, most people don't know about good commit messages when they join us, including very experienced developers :) Standards vary from project to project.

The most important part is the first line of your commit message - maintainers will use it to read through a large number of commits and thus it's important that it's short but most importantly concise. I'd heartily recommend reading http://coala.io/commit !

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Cheers!

**Comment by aptrishu** [comment]
Still working on this @achetan40 ? It's been a long time since you updated this PR.
A few things you should follow :- 
1. As this is a newcomer issue, we expect you to learn how to commit and generate a PR, and things like that. So, for that you should actively work on the issue. I'm not seeing any update or progress.
2. Learn how to write good commits follow the link [here](http://coala.io/commit) .

If you have any doubt ping us on our gitter channel. we'd be happy to help you.

**Comment by aptrishu** [comment]
Still on this ? @achetan40

**Comment by Adrianzatreanu** [comment]
closing due to high inactivity

**Pull request closed without merging**
