### PR TITLE
Use alabaster Theme

### PR DESCRIPTION
**Pull request by Mariatta**
Update conf.py to use alabaster theme. Customize the sidebar,
and add git repository information

Closes https://github.com/coala/documentation/issues/99

Hi, please check, and let me know what you think.

Do test it on your own environment first :) 
Thanks.

Here's how it looks like on my local env.
screen shot 2016-10-15 at 10 30 00 am

### CODE REVIEW

**Comment by sils** [comment]
Kudos for the screenshot :+1:

**Comment by sils** [comment]
Nice - can we have a star button instead of the watch button?

**Comment by SanketDG** [comment]
Also, can we get the banner removed? IMHO, when people want to visit the docs, they just want to visit the docs. Also it looks out of place. We can always use the WIP website for some eye candy 😉

**Comment by Mariatta** [comment]
Hmm.. not sure if I can change it to Star instead of Watch.
Let me tinker with it a bit more and get back to you :)

**Comment by Mariatta** [comment]
Sure, if we don't want the banner, I can remove it in the next commit :)

**Comment by Mariatta** [comment]
@SanketDG banner removed :)
screen shot 2016-10-15 at 11 39 58 am

**Comment by sils** [comment]
Can we have the search on top of the nav entries maybe?

**Comment by SanketDG** [comment]
> @SanketDG banner removed :)

@Mariatta really sorry for not being clear. What I meant was the top coala banner image, but I should get some opinions on that. CC @sils @Adrianzatreanu 

On the other hand, "Fork on Github" banner looks okay, but I see there is also a `github_button` thingy in http://alabaster.readthedocs.io/en/latest/customization.html#variables-and-feature-toggles, maybe we could so that to show a star widget (also watch and fork buttons maybe)? I prefer the buttons as this is more suitable for our usecase

**Comment by SanketDG** [comment]
Also, remember to point to `coala/coala` for the buttons.

**Comment by sils** [comment]
@SanketDG the top coala banner is another issue, please file an issue. We also had some discussion about making some default banners for all projects with @adtac , *please* get this going again. But not here.

**Comment by sils** [comment]
@Mariatta so the navigation poses one problem: it has like three different font sizes and that's visually a bit confusing. Maybe we can tweak that and make the headings (Home, For Users, ...) as big as the links?

**Comment by sils** [comment]
Also CC @beatrix-bodo who liked this to happen as well, in case she's interested to give some feedback as well.

**Comment by Mariatta** [comment]
Here's what I did so far:
- put back fork me banner
- changed the watch button to star
- moved up search box
- changed the github repo url from `coala/documentation` to `coala/coala`

Changing the repo url to `coala/coala` also automatically changed the "Fork me" link to `coala/coala` instead of `coala/documentation`. Is this ok?

screen shot 2016-10-15 at 12 03 48 pm

**Comment by Adrianzatreanu** [comment]
this is amazing :D 



however, why are there two different commits for this with the same name :D ? if they do different things, please mention in shortlog, if they dont, squash them :D

**Comment by Adrianzatreanu** [comment]
regarding the huge logo: my opinion is pro to keeping it, i like it, its eye candy.

regarding the theme: its amazing, i like this :D +111111111111 for giving us screenshots

**Comment by Makman2** [comment]
I'm also for keeping the image, makes docs entry page more comfy :D

And also from me @Mariatta , very well done :) :+1: :melon: 🍇

**Comment by Mariatta** [comment]
Thanks everyone 😀 
I added a custom css to change the fontsize of the sizebar heading, as per @sils suggestion.
Let me know if this works.

screen shot 2016-10-15 at 3 59 04 pm

**Comment by sils** [comment]
CC @fneu

**Comment by sils** [comment]
can you squash your commits together?

**Comment by sils** [comment]
and rebase? I'd be good to merge this I think :)

**Comment by sils** [comment]
(you can squash them with the interactive rebase, ask on coala.io/chat for help :))

**Comment by Mariatta** [comment]
Thanks @sils I squashed the commits.

**Comment by sils** [comment]
Hi,

it looks like your PR is out of date and needs a rebase. [This page](http://coala.io/git) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

(Be sure to use coala-bears on the coala-bears repository :))

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix it up for you - just tell us :).

Ping us on [our gitter channel](https://coala.io/chat) if you need help!

**Comment by sils** [comment]
(yes that's a template, hope it helps :P)

**Comment by sils** [comment]
ack https://github.com/coala/documentation/pull/194/commits/84dc0aad3d351a6197a9e55fdf90c5edfd961167

**Comment by sils** [comment]
We can merge it after the rebase

**Comment by Mariatta** [comment]
Thanks again @sils. I think I rebased it ok.

**Comment by sils** [comment]
ack https://github.com/coala/documentation/pull/194/commits/d517eebd8ebfbc125b3644e44c895319f6a5ab2d

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
