### PR TITLE
Netlify

### PR DESCRIPTION
**Pull request by jayvdb**
Modify location of `requirements.txt` so Netlify can find it, and add a `runtime.txt` to choose the Python version.

### CODE REVIEW

**Comment by yukiisbored** [comment]
ack https://github.com/coala/documentation/commit/4d8f6ffac0ef4a1c75b55415346b4ba3a63024ea

**Comment by yukiisbored** [comment]
ack https://github.com/coala/documentation/commit/4b7516784cbc2723499f8b02ab8f09ab6089e902

**Comment by jayvdb** [comment]
Mispelling in commit message.

**Comment by jayvdb** [comment]
reack https://github.com/coala/documentation/pull/497/commits/db599fde32fe526e38852b21baa75224cf8a3e0b https://github.com/coala/documentation/pull/497/commits/e7a8c8efa1b8a34eaaa19ca81e367e5d5010e0c4

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
