### PR TITLE
Closes #103

### LINKED ISSUE #103: Executing_Tests.rst: Remove redundant whitespace in shell command
https://github.com/coala-analyzer/documentation/blob/master/Developers/Executing_Tests.rst

change to
```
$ pip3 install -r test-requirements.txt  -r requirements.txt
# to -->
$ pip3 install -r test-requirements.txt -r requirements.txt
```

### PR DESCRIPTION
**Pull request by Dawny33**
Removed redundant whitespace in shell command in the Executing_Tests.rst file

### CODE REVIEW

**Comment by sils1297** [comment]
Hi,

it seems that your commit message doesn't contain enough information. Don't worry, most people don't know about good commit messages when they join us, including very experienced developers :) Standards vary from project to project.

The most important part is the first line of your commit message - maintainers will use it to read through a large number of commits and thus it's important that it's short but most importantly concise. I'd heartily recommend reading <http://coala.io/commit>!

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Cheers!

**Comment by sils1297** [comment]
(Please also note that you'll need a `Closes` instead of a `Fixes`, you can ask `cobot explain closes` on gitter for more info)

**Comment by Adrianzatreanu** [comment]
so in a nutshell: Your change itself is amazing and needed, but the commit message requires some work for us to maintain a clean history of commit messages, in case something will ever go wrong :)
check out the link @sils1297 gave you to find out how to write amazing commits in a few minutes, with examples there! :p

**Comment by Dawny33** [comment]
@sils1297 Updated the title. Would keep in mind for future patches :)

**Comment by Adrianzatreanu** [comment]
hey @Dawny33 thats totally not what he meant. first of all, his message is regarding your commit message, not your PR message (Commits get stored forever in history, PRs we dont care about them). we dont care about the PR, we care about the commits. he gave you a link that explains exactly what needs to be done to rework your commit message to be correctly done, and it also includes a Fixes/Closes somewhere (youll see what i mean after you read it), and @sils1297 mentioned that at that point, you should use Closes, not Fixes.

**Comment by Adrianzatreanu** [comment]
Ping on gitter if anything is unclear. btw this is the link im talking about http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html

**Comment by sils1297** [comment]
@Dawny33 why was this closed?

**Comment by Dawny33** [comment]
@sils1297 There was a problem with my setup then. So, I had closed this and opened a new PR properly: https://github.com/coala/documentation/pull/112

**Comment by sils1297** [comment]
ok

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala-analyzer.org/ - http://viperdev.io/ - http://gitmate.com/

**Pull request closed without merging**
