### PR TITLE
Newcomers_Guide.rst: Remove double newline

### PR DESCRIPTION
**Pull request by amrandahvur**
Closes https://github.com/coala/documentation/issues/182

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
this is not a bug, therefore use Closes instead of Fixes.

also, dont need to capitalize all words in shortlog (Double, Newline)

**Comment by amrandahvur** [comment]
@Adrianzatreanu Done :) Please Check ?

**Comment by Adrianzatreanu** [comment]
ack ea086b37c1096be544f4cf52f4a41fb35de0d57f

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Comment by Adrianzatreanu** [comment]
@amrandahvur amazing, could you please check coala.io/newform now and proceed to a low issue :D ? Thanks!

**Comment by amrandahvur** [comment]
@Adrianzatreanu Yes, In fact thats what I want to proceed with, I am having some troubles with setting up and installing stuff on my local machine though (especially dependencies listed in the docs), As soon as I get that right, I am getting my hands dirty on the low ones :D

**Pull request merged**
