### PR TITLE
Writing_Bears: fix typo in issue 232

### PR DESCRIPTION
**Pull request by lcrossan**

### CODE REVIEW

**Comment by Nosferatul** [comment]
Hey @lcrossan could you drop on gitter to invite you https://gitter.im/coala/coala? Also you should check your git config.
$ `git config --global user.name "John Doe"`
$` git config --global user.email johndoe@example.com`
Could you please check https://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html and after change your commit message? Thanks for the contribution. If you need help just ask us on https://gitter.im/coala/coala

**Comment by Nosferatul** [comment]
`Fixes` -> `Closes`

**Comment by Nosferatul** [comment]
also it appears your commits have no authorship. you should link your github account by using git config 
$ git config --global user.name "John Doe"
$git config --global user.email johndoe@example.com

**Comment by lcrossan** [comment]
changed the language. on my machine, it looks like my config is setup right:

```
$ git config --global user.name
-> lcrossan

$git config --global user.email
-> crossanlogan@gmail.com
```

**Comment by Nosferatul** [comment]
Seems like your email doesn't match. On git you have `lcrossan@dixonhill.com`

**Comment by lcrossan** [comment]
ah. that should be fixed now.

**Comment by Nosferatul** [comment]
ack 2434731

**Comment by Nosferatul** [comment]
@rultor merge

**Comment by Nosferatul** [comment]
in case you didn't already, can you help us by very quickly filling https://coala.io/newform ?

**Pull request merged**
