### PR TITLE
Sils/amelzer

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by Shade5** [comment]
Squashing the commits into one would be better right?

**Comment by sils** [comment]
no, why?

**Comment by rhemon** [comment]
changes seem fine to me, but about commit description if its related to any issue you are suggested to have "Fixes" and "Closes". you can see the explanation from the comment by gitmate-bot

@Shade5 I am not sure, but I think its fine since both are change in two different file following the guidelines

**Comment by sils** [comment]
there are no related.

**Comment by sils** [comment]
and squashing in this case would be bad, commits should be as small as possible, please don't ask contributors to squash commits that are good. Those two commits are different things and if they were squashed I would ask the contributor to split them up even.

**Comment by dracarys09** [comment]
The first commit could have a short description instead of just a shortlog

**Comment by sils** [comment]
it doesn't need one, it's a 4 character change and the shortlog makes everything obvious, I'd choose a good shortlog over a verbose body every time. The body is optional and usually only needed for complicated changes or if something is not obvious.

**Comment by sils** [comment]
I mean, what good is a body for this commit? It's just wasted time for the writer and the reader.

**Comment by Shade5** [comment]
Right, two commits are fine. LGTM

**Comment by dracarys09** [comment]
@sils what you said in https://github.com/coala/documentation/pull/385#issuecomment-271228223 makes sense to me... So after reading that I thing this PR is good to go.  :smile:

**Comment by sils** [comment]
so nobody wants to actually ack this?

**Comment by rhemon** [comment]
anyone can ack? 

ack 4474431 2826f16

**Comment by sils** [comment]
ack 4474431 2826f16

ack has to be at the start of the comment

**Comment by sils** [comment]
2826f16 ack

**Comment by sils** [comment]
@rultor merge

**Comment by rhemon** [comment]
oh ok, thanks, will keep this in mind next time

**Pull request merged**
