### PR TITLE
Install.rst: Update Documentation generation instructions

### PR DESCRIPTION
**Pull request by Uditgulati**
Updates the documentation generation command from ``make html`` to ``python setup.py docs``.

Closes https://github.com/coala/documentation/issues/523

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Uditgulati** [comment]
@EverWinter23 fixed :)

**Comment by khanchi97** [comment]
@Uditgulati you are making two PRs for a single issue https://github.com/coala/coala/issues/5062
If you need to make two commits for the same issue, you can make in a single PR, no need to open another PR for your second commit.

**Comment by Uditgulati** [comment]
@khanchi97  but they are for 2 different repos, how can they be done in one PR?

**Comment by khanchi97** [comment]
Oh okay, but now you also have to open the same issue in this repo, so that you can relate this PR to coala/documentation repo issue.I think this is how it should be done :)

**Comment by Uditgulati** [comment]
@khanchi97  Opened the issue in this repo and made the required amends to commit and PR.

**Comment by Makman2** [comment]
unack e7980eecbb826629bbc69f1d711724270b04a811

**Comment by Makman2** [comment]
Do not merge until issue is confirmed, it seems to be invalid.

**Comment by Makman2** [comment]
Invalid issue, closing.

**Pull request closed without merging**
