### PR TITLE
Install.rst: Install virtualenv with --user

### PR DESCRIPTION
**Pull request by lilithxxx**
Updates documentation to tell user to Install virtualenv with --user and how to check whether its already installed.

Closes https://github.com/coala/coala/issues/4017

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by lilithxxx** [comment]
I made this PR referencing issue https://github.com/coala/coala/issues/4017#

It tells user to Install virtualenv with --user and how to check whether its already installed

**Comment by lilithxxx** [comment]
I made a new PR ->https://github.com/coala/documentation/pull/524.

You can check it out @newbazz

**Comment by newbazz** [comment]
Dont close a PR unnecessarily.

**Comment by Makman2** [comment]
@lilithxxx Please don't close PRs, next time I will close any new PRs for the same issue from you and reopen the old ones^^ Please read up on how to rebase properly and amend commits.

**Comment by lilithxxx** [comment]
@Makman2  I am sorry for closing the PRs but I closed the last one because I was told to do so as my commit was from the master branch.
I won't close PRs anymore. Sorry for the inconvenience.
You can check my final PR https://github.com/coala/documentation/pull/525

**Pull request closed without merging**
