### PR TITLE
Closes #103

### LINKED ISSUE #103: Executing_Tests.rst: Remove redundant whitespace in shell command
https://github.com/coala-analyzer/documentation/blob/master/Developers/Executing_Tests.rst

change to
```
$ pip3 install -r test-requirements.txt  -r requirements.txt
# to -->
$ pip3 install -r test-requirements.txt -r requirements.txt
```

### PR DESCRIPTION
**Pull request by Dawny33**
Removed redundant whitespace in shell command in the Executing_Tests.rst file

### CODE REVIEW

**Comment by sils1297** [comment]
Same thing with the commit message here.

**Comment by Dawny33** [comment]
@sils1297 Pl review :)

**Comment by Adrianzatreanu** [comment]
holy, the shortlog is 66 characters long, the limit is 50 characters, you need to shorten it a bit.

@sils1297 why is GitCommitbear not saying anything?

**Comment by sils** [comment]
@Dawny33 are you still on this? This needs a rebase and the changes pointed out.

**Comment by sils** [comment]
Actually it seems someone else took over the issue while you were away. Closing the PR thus.

**Pull request closed without merging**
