### PR TITLE
/Help/FAQ.rst : fix a broken link

### PR DESCRIPTION
**Pull request by athulpn**
/Help/FAQ.rst : fix a broken link

ask us link in 'installation is failing! help' section
 was fixed which otherwise gave 404 error

closes https://github.com/coala/documentation/issues/492

### CODE REVIEW

**Comment by athulpn** [comment]
why is there no process label in my pr.

**Comment by nkprince007** [comment]
Please fix your commit message @athulpn. Follow the guide [here](https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html).

**Comment by nkprince007** [comment]
unack https://github.com/coala/documentation/pull/506/commits/e43ffc7abf7f0dd83330f25a33e7eb60bb8b6c87

**Comment by athulpn** [comment]
@nkprince007  I corrected my commit message. What to do now

**Comment by nkprince007** [comment]
I don't see the change yet. @athulpn 😅

**Comment by athulpn** [comment]
@nkprince007  sorry..didn't get you. I changed my commit message. I am new here.

**Comment by athulpn** [comment]
Can anybody tell what is wrong with  this pr.

**Comment by realslimshanky** [comment]
@athulpn you need to use `git commit -a --amend` to fix your commit message as stated by @nkprince007 and the use `git push --force <remote> <branch>` to push your changes.

**Comment by athulpn** [comment]
@realslimshanky I am not getting my commit message when i issue that command. It is showing someone else message

**Comment by realslimshanky** [comment]
@athulpn make sure you are on the same branch which you used to make this PR.

**Pull request closed without merging**
