### PR TITLE
Developers/External_Bears : Balance the braceson the C++ code in the …

### LINKED ISSUE #305: C++ code on Developers/External_Bears has unbalanced braces
Opened via [gitter](https://gitter.im/coala/coala/?at=582b12d565485ebc679b0741) by @jayvdb

### PR DESCRIPTION
**Pull request by akshatnitd**
Developers/External_Bears.rst

A curly brace was missing in the C++ code
Fixes #305

### CODE REVIEW

**Comment by jayvdb** [comment]
Doesnt follow commit message guideline.

**Comment by akshatnitd** [comment]
@jayvdb Did the changes according to the guidelines

**Comment by srisankethu** [comment]
@akshatnitd Don't you think it should be ``Fixes`` since its a bug rather ``Closes``. Otherwise the PRs good :+1:

**Comment by srisankethu** [comment]
ack https://github.com/coala/documentation/pull/307/commits/c26663e4b28be58e68484b98d410a897db625334

**Comment by srisankethu** [comment]
@rultor merge

**Comment by akshatnitd** [comment]
@rultor @srisankethu Happy to see my first PR merge :smile:

**Comment by jayvdb** [comment]
👍

**Pull request merged**
