### PR TITLE
Writing_Good_Commits: Add a dot

### PR DESCRIPTION
**Pull request by tamj0rd2**
For consistency.

Closes https://github.com/coala-analyzer/documentation/issues/66

### CODE REVIEW

**Comment by sils1297** [comment]
@Adrianzatreanu this is not a bug, it's a pr

**Comment by sils1297** [comment]
Fixes -> Closes, remove colon.

I only have a few seconds, ask people on gitter for full explanation - sorry :/

**Comment by Adrianzatreanu** [comment]
oh its a PR :D yeah, as lasse said: ``Fixes: link`` -> ``Closes link``

**Comment by sils1297** [comment]
The most important part is the first line of your commit message - maintainers will use it to read through a large number of commits and thus it's important that it's short but most importantly concise. I'd heartily recommend reading http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html !

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

**Comment by sils1297** [comment]
@tamj0rd2 any news?

**Comment by tamj0rd2** [comment]
@sils1297 Had a problem with my git. Fixed now :)

**Comment by Adrianzatreanu** [comment]
You still need to change Fixes to Closes, as this is not a bug :)

**Comment by tamj0rd2** [comment]
@Adrianzatreanu I've finally updated the commit

**Comment by Adrianzatreanu** [comment]
Hi,

it looks like your PR is out of date and needs a rebase. [This page](http://coala.io/git) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

We also have a quick video tutorial on how to rebase: [https://asciinema.org/a/78683](https://asciinema.org/a/78683). That should help you understand the basics of how it works and what you should be doing.

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

(Be sure to use the coala-bears URL if you're on coala bears!)

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix it up for you - just tell us :).

Ping us on [our gitter channel](https://coala.io/chat) if you need help!

**Comment by tamj0rd2** [comment]
I've rebased it now :)

**Comment by Adrianzatreanu** [comment]
ack 1d587be2fcbd13fd6445ed9e731bbd91b74f9a23

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Comment by Adrianzatreanu** [comment]
hey, @tamj0rd2 , could you please take a few moments and fill this in? id love if you could: coala.io/newform

**Pull request merged**
