### PR TITLE
PULL_REQUEST_TEMPLATE.md : fix a typo 

### PR DESCRIPTION
**Pull request by athulpn**
PULL_REQUEST_TEMPLATE.md : fix a typo

'cobot' was changed to 'corobo'

Closes https://github.com/coala/documentation/issues/503

### CODE REVIEW

**Comment by athulpn** [comment]
@newbazz  fixed

**Comment by newbazz** [comment]
http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html read this and change your commit msg :)

**Comment by athulpn** [comment]
I read it . It seems fine. Please try to specify what is wrong as I am new here. @newbazz

**Comment by newbazz** [comment]
@athulpn https://github.com/coala/documentation/pull/507/commits is ur commit message but 
image this should be your commit message. got it?

**Comment by athulpn** [comment]
Thanks @newbazz

**Pull request closed without merging**
