### PR TITLE
Developers/Writing_Good_Commits.rst: Deleted Repeated "and"

### PR DESCRIPTION
**Pull request by Akki356**
Deleted repeated "and" from the following sentence
"Should have a tag and and a short description separated by a colon"
in Writing_Good_commits.rst

Fixes https://github.com/coala/documentation/issues/151

### CODE REVIEW

**Comment by Nosferatul** [comment]
Hello @Akki356 ! `Fixes` -> `Closes` . We use `Fixes for bugs!

**Comment by Nosferatul** [comment]
The commit message looks good to me 👍

**Comment by Adrianzatreanu** [comment]
Hey, we usually allow newcomers to only fix one newcomer issue, as their purpose is to learn the workflow, and they are truly easy. You currentl have PRs open for two newcomer issues, could you please choose one of them and close the other PR?

**Comment by amrandahvur** [comment]
Hey, IMO you should use "Closes" instead of "Fixes" as it isn't a real bug.
Follow this procedure to change the commit message,

To change your message you just use git commit --amend and then git push --force the new commit to replace the old one.

Also, IMO use double backticks for the keyword 'and' in your commit message.
i.e "and" ---> ``and``

**Comment by sils** [comment]
I'd strip the `Developers/` from the first line of commit message (shortlog)

**Comment by sils** [comment]
Fix those things, do a rebase and this is good to go. Let us know if you need anything!

**Comment by Nosferatul** [comment]
Hey! You should rebase!
Take a look -> https://docs.coala.io/en/latest/Developers/Git_Basics.html

**Comment by Nosferatul** [comment]
@Akki356 you aren't assign to https://github.com/coala/documentation/issues/151. Please remove the commit https://github.com/coala/documentation/pull/200/commits/8f183c354fc51045eab350f1749e8cc35739f033  and rebase, if you need help use `cobot explain rebase` on gitter or ask there for help!

**Comment by aptrishu** [comment]
Please follow `writing good commits` guideline [here](http://coala.io/commit) .

**Pull request closed without merging**
