### PR TITLE
Developers/Newcomers_Guide: Fix broken link

### LINKED ISSUE #129: Developers' Newcomers Guide has a broken link to low issue
In http://coala.readthedocs.io/en/latest/Developers/Newcomers_Guide.html

Step 7 >

Congratulations! Your PR just got accepted! You’re awesome. Now you should go for a **[low issue](http://coala.readthedocs.io/en/latest/Developers/tinyurl.com/coala-low)**, they are really rewarding!

URL to coala low issue is broken.

File: https://github.com/coala/documentation/blob/e45e9478aac5f776656b81c9a950aa816f3f4180/Developers/Newcomers_Guide.rst

### PR DESCRIPTION
**Pull request by dip-kush**
In http://coala.readthedocs.io/en/latest/Developers/Newcomers_Guide.html

Step 7 >

Congratulations! Your PR just got accepted! You’re awesome. Now you should go for a [low issue](http://coala.readthedocs.io/en/latest/Developers/tinyurl.com/coala-low) they are really rewarding!

URL to coala low issue is broken.

### CODE REVIEW

**Comment by srisankethu** [comment]
@dip-kush adding `http://` doesn't make any difference. It is still broken. If you open tinyurl.com/coala-low, you will see in the search bar ``user: coala-analyser``. The organisation was coala-analyser earlier which changed to coala. Change ``user: coala-analyser`` to ``user: coala`` and search. Make a tinyurl out of the new link and replace with the old link.
Can you also change the commit message to something like "Developers/Newcomers_Guide: Fix broken link" and then link the issue.
You can do that by `git commit --amend -a -m "Developers/Newcomers_Guide: Fix broken link" -m "Fixes #129"`.

**Comment by sils1297** [comment]
Thanks for the review @srisankethu , well appreciated!

**Comment by dip-kush** [comment]
@srisankethu  Thanks for the review. 
Fixed the broken link by creating a new tinyurl [ http://tinyurl.com/coala-low-issues ] and changed the commit message to the desired one.

**Comment by sils1297** [comment]
can you use coala.io/low instead?

**Comment by sils1297** [comment]
(don't bother changing the PR title btw. we don't care about it, only about the commit)

**Comment by sils1297** [comment]
also in the commit message, please use the full URL to the issue so the link sill works when we move the repo e.g. to gitlab or when browsing the repo locally

**Comment by Adrianzatreanu** [comment]
hey, the merge commit appeared because you did not rebase successfully. we cant merge with that commit. please follow this tutorial to how to rebase correctly:


Hi,

it looks like your PR is out of date and needs a rebase. [This page](http://coala.io/git) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

We also have a quick video tutorial on how to rebase: [https://asciinema.org/a/78683](https://asciinema.org/a/78683). That should help you understand the basics of how it works and what you should be doing.

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

(Be sure to use the coala-bears URL if you're on coala bears!)

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix it up for you - just tell us :).

Ping us on [our gitter channel](https://coala.io/chat) if you need help!

**Comment by dip-kush** [comment]
Now It should be able to merge. I have synced my fork.

**Comment by srisankethu** [comment]
@dip-kush hasn't @sils1297 suggest you to use `coala.io/low` instead?

**Comment by dip-kush** [comment]
Updated the link with https://coala.io/low

**Comment by dip-kush** [comment]
I have synced my fork again

**Comment by Adrianzatreanu** [comment]
ack 3783ef8

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
