### PR TITLE
Correct grammatical error: an user --> a user

### PR DESCRIPTION
**Pull request by ShivamSinghania**
index.rst: Correct grammatical error

This corrects the typo and changes it from an user --> a user.

Closes https://github.com/coala/documentation/issues/516

### CODE REVIEW

**Comment by khanchi97** [comment]
@ShivamSinghania Please follow our [commit guidelines](https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html), after you read these guidelines your commit should seems something like this:
`index.rst: Correct grammatical error`
and use `Closes issues_link` if you think you are not fixing any bug and if you feel you fixed a bug then use `Fixes issue_link` in your commit description.

**Comment by khanchi97** [comment]
and make sure in your commit message you are using only present tense 😉

**Comment by ShivamSinghania** [comment]
@khanchi97 I have read the commit guidelines and edited this commit.

**Comment by khanchi97** [comment]
No.The thing that you have changed is description in your PR.I meant to change your commit using `git commit --amend`

**Comment by ShivamSinghania** [comment]
Did I do it correctly this time ?

**Comment by Makman2** [comment]
I mean grammatical problems are usually mistakes and no "errors", but it's fine, everybody gets that :P

**Comment by Makman2** [comment]
ack 113d47b0aea4c58e18a3b0b34584907df8891aa6

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
