### PR TITLE
Writing_Good_Commits.rst: Changed message

### PR DESCRIPTION
**Pull request by OctavianGuzu**
Closes https://github.com/coala/documentation/issues/148

### CODE REVIEW

**Comment by Nosferatul** [comment]
Please change the authorship

**Comment by Adrianzatreanu** [comment]
Hey, you need to setup authorship with git (something with git config --global or so, google it) so the commits become yours.
Also, your commit message doesnt match our guidelines (coala.io/commit), please change the first line to imperative tense, as in "Changed"->"Changes"

**Comment by Mixih** [comment]
@OctavianGuzu You git user name and email must match you github username and email.

**Comment by Mariatta** [comment]
@OctavianGuzu Are you still working on this? 
If so, please recreate the PR in coala/coala repository.
The Developers section has been moved there in https://github.com/coala/coala/issues/3133

If you are not working on it anymore, we can unassign #148 so other newcomers can take it on.

Thanks.

**Comment by Adrianzatreanu** [comment]
closing due to high inactivity

**Pull request closed without merging**
