### PR TITLE
conf.py: Update copyright year

### PR DESCRIPTION
**Pull request by saurabhmarpadge**
Change year 2016 to 2017.
Closes https://github.com/coala/documentation/issues/417

### CODE REVIEW

**Comment by satwikkansal** [comment]
Would be better to have commit message like 
```
conf.py: Update copyright year

Change the Copyright year from 2016 to 2017.
```
Please see https://coala.io/commit

**Comment by saurabhmarpadge** [comment]
Changed the commit message

**Comment by tabias** [comment]
Still missing the description and the closing url, you changed the PR title instead.

A commit message consists of 2 parts, the shortlog and the description
please read the user guide thoroughly to understand this, it's essential to functional operations with this many people (https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html).

> shortlog:
>> filename: Functional description

> Description 
>> Explaining the cause and solution

> Closes or Fixes github-url of the issue (#417)

**Comment by saurabhmarpadge** [comment]
Ok, Now added a Description and Closing Issue.

**Comment by damngamerz** [comment]
ack 9cb46b605847893a288f8359dab00d9663648a0a

**Comment by saurabhmarpadge** [comment]
thanks guys for getting me familiarize with the workflow.

**Comment by sahilarora535** [comment]
unack 9cb46b605847893a288f8359dab00d9663648a0a

**Comment by damngamerz** [comment]
@sahilarora535 Does it really make a difference? cause short log already specifies where the change is gonna be.I think it's fine.

**Comment by saurabhmarpadge** [comment]
@sahilarora535, is there any thing remaining

**Comment by sahilarora535** [comment]
@damngamerz The commit body had a grammatical error, had it been `Change year from 2016 to 2017`, it would have been understandable. However, the 'from' was missing from the body, hence I thought it would be better to make a further improvement. :)
@saurabhmarpadge Rest is cool. :D

**Comment by sahilarora535** [comment]
@saurabhmarpadge To make the change in your commit message, just amend your commit using `git commit --amend`, and then do a force push using `git push -f`. Everything we be handled automagically. :smile:

**Comment by saurabhmarpadge** [comment]
Ok, fine at least now accept my PR. It's my first PR after all.

**Comment by saurabhmarpadge** [comment]
This issue was labeled newcomer as well as low. So, now am I allowed to work on difficulty/low or I have to move on the medium difficulty.

**Comment by sahilarora535** [comment]
ack 438aa4c88d2bf7c26ff9208c8a06b55b52947f11

**Comment by Siddhartha1234** [comment]
ack 438aa4c

**Comment by damngamerz** [comment]
Hey I just noticed you are not assigned to this issue https://github.com/coala/documentation/issues/417
Please get it assigned to yourself just type `cobot assign <issue_url>` in out gitter chat channel.

**Comment by saurabhmarpadge** [comment]
I did last time but it didn't work. Oh I see now you have to mention URL only issue id won't be enough.

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
