### PR TITLE
Updated Newcomers guide

### PR DESCRIPTION
**Pull request by Scapogo**
Added note that user should be logged in before clicking on Newcomers link.

### CODE REVIEW

**Comment by sils** [comment]
Commit message: newcommer -> newcomer

**Comment by sils** [comment]
Hi,

it seems that your commit message does need some work. Don't worry, most people don't know about good commit messages when they join us, including very experienced developers :) Standards vary from project to project. This is actually pretty close.

The most important part is the first line of your commit message - maintainers will use it to read through a large number of commits and thus it's important that it's short but most importantly concise. I'd heartily recommend reading <http://coala.io/commit>!  Try describing your change, not just "updated", e.g. `Newcomers: Add GitHub login note` as shortlog. Also add a `Closes <issue_url>` note.

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Cheers!

**Comment by Scapogo** [comment]
Hi,

 I just changed that message. Hopefully it is much better now :)

**Comment by sils** [comment]
@Scapogo you have to change your commit, not the PR, see instructions ;)

**Comment by Scapogo** [comment]
Sorry, it is my first pull request... I just changed commit message and I hope it is fine now.

**Comment by chauffer** [comment]
Don't worry!
However, it seems you've mistakenly left the previous commit message in there; so now it's:

```
Updated Newcomers guide

Newcomers: Added note the user should be logged in before clicking on Newcomers link.
Closes coala#251
```


It should look something like:

```
Newcomers: Add GitHub login note

Closes https://github.com/coala/documentation/issues/251
```

**Comment by chauffer** [comment]
ack f840972

**Comment by underyx** [comment]
@rultor merge

**Pull request merged**
