### PR TITLE
Writing_Tests: Add `uut` under glossary section

### PR DESCRIPTION
**Pull request by meetmangukiya**

### CODE REVIEW

**Comment by aptrishu** [comment]
Could you define that somewhere else.? I mean anywhere in this page where uut is written (like this uut(Unit Under Test)), we shouldn't make a separate section `Glossary` unless we have more abbreviations to define there. looks odd.

**Comment by sils** [comment]
I don't think we'llhave more abbrevs coming, maybe terms. Not sure. I'm fine with the commit though.

**Comment by meetmangukiya** [comment]
So, no edit needed?

**Comment by jayvdb** [comment]
ack e673f36

**Comment by jayvdb** [comment]
@rultor merge

**Comment by jayvdb** [comment]
We can always improve it later.
More important things to think about now.

**Pull request merged**
