### PR TITLE
coafile.rst : Explanation or Clarification line added

### PR DESCRIPTION
**Pull request by animenon**
- Explanation about comment in the middle of a value added.
- A line of explanation on what the key and value would be post execution of those lines.

### CODE REVIEW

**Comment by RaiVaibhav** [comment]
Read the [NewCommer Guide line](http://api.coala.io/en/latest/Developers/Newcomers_Guide.html) first.<br />
maintainers please close this PR

**Comment by animenon** [comment]
@RaiVaibhav  Its a minor commit, no issue is linked to it. 
If you feel the PR is to be closed, I shall close it. Anyhow I don't see any of the collaborators merging it. And `corobo` was not helpful on the gitter channel, tried 2-3 commands none worked.

**Comment by RaiVaibhav** [comment]
@animenon  thats why i cut my comment

**Comment by Monal5031** [comment]
@animenon Please go through our newcomers guide to know how to start contributing to this repository.
Also, it is essential to create an issue before sending any PR (So please create one first) and reference it in this PR.
If at any moment you feel you are stuck on something ask on gitter channel someone will help you.

**Comment by animenon** [comment]
@Monal5031 The fix is minor, just a comment add. Its seems too long a process to create an issue, get it assigned and then wait for review comments. Hence closing PR.

**Pull request closed without merging**
