### PR TITLE
coala_as_Git_Hook.rst: Complete underline

### PR DESCRIPTION
**Pull request by tabias**
Warning generated from rstcheck:
Title underline was 1 character short

fixes https://github.com/coala/documentation/issues/246

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
Hey, your change is okay but your commit message is not. We have some guidelines,
and it would take you less than 5mins to read them around here coala.io/commit
Basically the wrong lines are the shortlog and the "fixes" one :) please read the link, thanks!

@sils why didnt gitmate catch the bad regex?

**Comment by sils** [comment]
not sure, is the regex defined correctly?

**Comment by tabias** [comment]
updated the commit shortlog and message.

**Comment by all3fox** [comment]
ack 87dfb1d569b73e50de90fe8d7d4f185029ba0591

**Comment by Techievena** [comment]
@arnab1896 it is a bug IMO

**Comment by arnab1896** [comment]
@Techievena , my bad :worried: 
in that case @tabias ;
 'fixes' is okay
Cheers

**Comment by all3fox** [comment]
@arnab1896 don't worry about that. However, next time please think that ([source][1]):

> In some situations, e.g. bugs overcome in documents, the difference between Fixes and Closes may be very small and subjective. If a specific issue may lead to an unintended behaviour from the user or from the program it should be considered a bug, and should be addresed with Fixes.

And even though this change is not really a bug, the distinction is so blurred that I do not see any point in making it :)

[1]: http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html

**Comment by tabias** [comment]
in my opinion there is a distinction:

a bug is a feature or a given that disrupts the intended function (requiring Fixes)

a feature/enhancement is an addition resulting in an improvement (requiring Closes)

linked issue: #418

**Comment by satwikkansal** [comment]
Is this a bug `rstcheck`? because the earlier version looks good to me

**Comment by SanketDG** [comment]
@myint is this normal?

AFAIK 

> The underline/overline must be at least as long as the title text.

**Comment by myint** [comment]
I can't reproduce this.

`foo.rst`:
```rst
Git Hooks
=========
```

```
$ rstcheck foo.rst
```

It only complains if it is actually too short.

`bar.rst`:
```rst
Git Hooks
========
```

```
$ rstcheck bar.rst
bar.rst:2: (WARNING/2) Title underline too short.
```

I'm curious about what package versions you are using.

```
$ rstcheck --version
rstcheck 3.0

$ pip3 freeze | grep docutils
docutils==0.13.1
```

**Comment by myint** [comment]
Never mind. I can reproduce it if I directly download that file.

```
$ file coala_as_Git_Hook.rst
coala_as_Git_Hook.rst: UTF-8 Unicode (with BOM) text

$ rstcheck coala_as_Git_Hook.rst
coala_as_Git_Hook.rst:2: (WARNING/2) Title underline too short.
```

I guess `docutils` doesn't like the BOM. Maybe it misleads it to think that there is an actual visible character at the beginning of the file before the `Git Hooks` title.

**Comment by myint** [comment]
Please try https://github.com/myint/rstcheck/pull/24 to work around this docutils bug. I can merge it once Travis CI recovers from the S3 problem.

**Comment by SanketDG** [comment]
@tabias, this issue has a different fix as you can see, so feel free to close this PR. You can look at other newcomer issues here http://coala.io/new

**Comment by tabias** [comment]
it's very hard do distinct an issue like this in a repo versus the tools that are used. Regardless, I'll close the PR. It should be wise for someone posting an issue to look at possible solution prior to posting an issue (in this case the tool is hacked/fixed) to circumvent the error.

**Comment by myint** [comment]
This is fixed in rstcheck 3.0.1.

**Pull request closed without merging**
