### PR TITLE
Update Writing_Good_Commits.rst

### LINKED ISSUE #149: Developers/Writing_Good_Commits.rst: In order to do that we are ... (Reword)

### PR DESCRIPTION
**Pull request by Pranav-Jain**
Writing_Good_Commits.rst: Change a line

Initially the line said "In order to do that we are verifying that
every change to our code (i.e. the commits) is making it better.".
Changed it to "Therefore we are ensuring that every change to
our code (i.e. the commits) will make it better" to improve its meaning.

Closes #149

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
hey please check all the gitmate points, because your commit message is not good according to our guidelines! thanks

**Comment by aptrishu** [comment]
Hey @pranav16255 , Please close this PR because you have generated another PR for the same.
@Adrianzatreanu

**Comment by aptrishu** [comment]
Still on this ? @Pranav-Jain

**Comment by Adrianzatreanu** [comment]
closing due to high inactivity

**Pull request closed without merging**
