### PR TITLE
fix-Writing_Good_Commits-missing-blank-line

### PR DESCRIPTION
**Pull request by charlesBak**
add blank line #248

### CODE REVIEW

**Comment by Nosferatul** [comment]
Hey, you need some changes on the commit message. Please take a look at https://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html. Also `Fixes` -> `Closes`

**Comment by charlesBak** [comment]
@Nosferatul i new at open source, can you tell for example what would be a good commit for this issue?

**Comment by Nosferatul** [comment]
Sure:
`Writing_Good_Commits: missing blank line`

`Adds blank lines.`

`Closes -> https://github.com/coala/documentation/issues/248`

Something like this. Overall you have a good commit message, needs only a little adjustment

**Comment by charlesBak** [comment]
thank you @Nosferatul

**Comment by Nosferatul** [comment]
Sure 😄

**Comment by aptrishu** [comment]
Still on this ? @charlesBak

**Comment by Adrianzatreanu** [comment]
closing due to high inactivity

**Pull request closed without merging**
