### PR TITLE
Update coala_as_Git_Hook.rst

### PR DESCRIPTION
**Pull request by souradeeptab**
The fourth line was reading as "This document is a guide on how to add coala as a git hook. Using git hooks"
Its has now been updated to "This document is a guide on how to add coala as a git hook. Using a git hook,"
The sentence now reads as " Using a git hook, coala can be executed automatically, ensuring your code follows your quality requirements. "

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
Hey, it seems your commit message requires a little work. Could you read this first please :D ?coala.io/commit Thank you!

**Comment by Nosferatul** [comment]
Hi @souradeeptab . You should take a look -> https://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html

**Comment by sils** [comment]
@souradeeptab are you still on this? Is there an issue associated with this? Can you please at least tell us if you're not working on it anymore so we can give it someone else?

**Comment by souradeeptab** [comment]
Hi,
I am deeply apologize for not being able to answer. I will handle this
today itself and fix the pull request with the commit message.
I actually fell sick and was AFK for a few weeks. I will fix this up by
today.
Again, I apologize for not being prompt.

On Mon, Oct 17, 2016 at 10:22 AM, Lasse Schuirmann <notifications@github.com

**Comment by souradeeptab** [comment]
@sils Should I raise a new Pull Request for this issue with the updated commit message ?

**Comment by sils** [comment]
you can change your message with git commit --amend and then push it with
git push --force to change your existing PR, that should be way simpler -
ask on coala.io/chat if you need further git help

**Comment by aptrishu** [comment]
Hey @souradeeptab , A few things you should follow :- 
1. As this is a newcomer issue, we expect you to learn how to commit and generate a PR, and things like that. So, for that you should actively work on the issue. I'm not seeing any update or progress.
2. Learn how to write good commits follow the link [here](http://coala.io/commit).

**Comment by aptrishu** [comment]
Still on this ? @souradeeptab

**Comment by souradeeptab** [comment]
This was closed by someone else before assignment @aptrishu
<https://github.com/aptrishu>

**Comment by jayvdb** [comment]
This change has been done. See https://github.com/coala/documentation/blob/master/Users/coala_as_Git_Hook.rst

**Pull request closed without merging**
