### PR TITLE
Glob_Patterns.rst: Change string from looses to loses

### PR DESCRIPTION
**Pull request by athend**
Switching all instances of word looses to loses
to reflect the desired and correct meaning

Closes https://github.com/coala/documentation/issues/118

### CODE REVIEW

**Comment by Nosferatul** [comment]
Fixes -> Closes. We use Fixes for bugs.

**Comment by Adrianzatreanu** [comment]
it appears you havent setup your git account properly, as it doesnt have your authorship. please do so :D

**Comment by athend** [comment]
Oh! I was working on a VM and forgot to set authorship!

**Comment by Adrianzatreanu** [comment]
hey it seems that there are unwanted commits (such as the one without authorship and the merge one).. could you please remove them by rebasing :D ? thanks. if you dont know how to rebase, let me know.

**Comment by Dayfiri** [comment]
Is this issue still going ?

**Comment by sils** [comment]
What do you mean with "still going"?

**Comment by sils** [comment]
Ah.

@athend you still working on this?

**Comment by aptrishu** [comment]
Still working on this ? @athend

**Comment by athend** [comment]
Sorry for not working on this for a long while.

I'll get working on this from a clean branch, if that's acceptable.

**Comment by Nosferatul** [comment]
You just need to rebase it, on gitter use `cobot explain rebase` this should help you! 👍

**Comment by aptrishu** [comment]
Still on this ? @athend 
We haven't seen any progress in this PR. Are you facing any problem? Feel free to ping us on our Gitter channel. https://gitter.im/coala/coala

**Comment by jayvdb** [comment]
#118 has already been completed by someone else.

**Pull request closed without merging**
