### PR TITLE
Newcomers_Guide.rst: Change testing bears link

### PR DESCRIPTION
**Pull request by divyam3897**
Fixes https://github.com/coala/documentation/issues/127

### CODE REVIEW

**Comment by srisankethu** [comment]
Change from the commit message from `Closes link` to `Fixes link` since broken links are considered as bugs.

**Comment by Adrianzatreanu** [comment]
hey, could you please ask to be assigned next time? else there might be people working ont he same issues...

**Comment by Adrianzatreanu** [comment]
ack 05a509

**Comment by Adrianzatreanu** [comment]
ack 905a509

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
