### PR TITLE
Writing_Bears: Add period to list item

### PR DESCRIPTION
**Pull request by j0br13n**
Unifying grammatical ending of list items for the "Communicating with the User" section.

Closes https://github.com/coala/documentation/issues/233

### CODE REVIEW

**Comment by AbdealiJK** [comment]
Fix looks good. But commit message needs some work. please read the docs:

Hey,

We use some bug prediction in coala which relies on the `Fixes` keyword in commit messages. To get good results from that we need to use `Closes` for normal issues instead of `Fixes` which should only be used for real bugs. (See also [the commit message docs](http://coala.io/commit).)

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Cheers!

------------

Hi,

It seems that your commit message doesn't contain enough information. Don't worry, most people don't know about good commit messages when they join us, including very experienced developers :) Standards vary from project to project.

The most important part is the first line of your commit message - maintainers will use it to read through a large number of commits and thus it's important that it's short but most importantly concise. I'd heartily recommend reading http://coala.io/commit !

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Cheers!

----------

**Comment by j0br13n** [comment]
Updated commit message to user 'Closes' instead of 'Fixes'

**Comment by sils** [comment]
ack https://github.com/coala/documentation/pull/245/commits/e5a33f31c60bf4c1b52a60d4a3dac2a86deae3a0

**Comment by sils** [comment]
Hi,

it looks like your PR is out of date and needs a rebase. [This page](http://coala.io/git) may help you to get started on this. (*Do not press the update branch button. It's evil.*) Otherwise it's good to go!

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

(Be sure to use coala-bears on the coala-bears repository :))

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix it up for you - just tell us :).

Ping us on [our gitter channel](https://coala.io/chat) if you need help!

**Comment by sils** [comment]
Hey, you didn't rebase your commit - are you aware?

**Comment by sils** [comment]
seems that your os x commit is already done by some other contributor and merged on master

**Comment by j0br13n** [comment]
Had some issues trying to figure out how to back out the os x commit - I dropped my previous fork and started from scratch - please see PR #263 for the replacement PR  to close this out.  - sorry for the confusion here and thanks for your patience!!

**Pull request closed without merging**
