### PR TITLE
FAQ.rst: Add ToC

### PR DESCRIPTION
**Pull request by Warewolf96**
Add Table of contents in FAQ.rst

Closes https://github.com/coala/documentation/issues/285

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
this appears to need a rebase

**Comment by Warewolf96** [comment]
@Adrianzatreanu i am doing rebase but it shows everything is up-to-date

**Comment by Warewolf96** [comment]
@sils I guess this is rebased, can u please check?

**Comment by satwikkansal** [comment]
ack 014b26a

**Comment by jayvdb** [comment]
@rultor merge

**Comment by Warewolf96** [comment]
@dracarys09 Done :)

**Comment by dracarys09** [comment]
ack d409dab5012bb0bcfc6d15b65d83cee5557c6aa6

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
