### PR TITLE
Update Writing_Linter_Bears.rst

### PR DESCRIPTION
**Pull request by rishus23**
Add reference link to coala API docs for further linter decorator readings.

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
the commit shortlog contains almost no useful information, could you please read coala.io/commit and ammend it :)? Thanks!

**Comment by Adrianzatreanu** [comment]
hey.. you didnt need to create 2 commits, we dont want them both. you needed to edit your previous one instead with git commit --amend. now you will need to rebase and remove one, using "git rebase -i origin master",  ask on gitter or look for it on google :)

**Comment by rishus23** [comment]
I'm not doing it locally, I'm doing it on github. OK , I'll inform you once I delete the previous commit.

**Comment by Adrianzatreanu** [comment]
basicalyl this it the tutorial, but when you do the interactive rbbase, you also remove one of the lines iwth one of the commits:


Hi,

it looks like your PR is out of date and needs a rebase. [This page](http://coala.io/git) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

We also have a quick video tutorial on how to rebase: [https://asciinema.org/a/78683](https://asciinema.org/a/78683). That should help you understand the basics of how it works and what you should be doing.

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

(Be sure to use the coala-bears URL if you're on coala bears!)

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix it up for you - just tell us :).

Ping us on [our gitter channel](https://coala.io/chat) if you need help!

**Pull request closed without merging**
