### PR TITLE
custom.css: Add styling to various components

### PR DESCRIPTION
**Pull request by hemangsk**
**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by satwikkansal** [comment]
Maybe you can add screen-shots of your changes, so it's easier to visualize and review.

**Comment by hemangsk** [comment]
Sure! 

- Dark background in the Note Block
- Font weights



- Header image



- Code Blocks

**Comment by sils** [comment]
ack https://github.com/coala/documentation/pull/413/commits/a6661783c9b18595a5e5886c220dd4e036c3cdf6

**Comment by sils** [comment]
ack https://github.com/coala/documentation/pull/413/commits/ef6b538317e1ff884028064e874cd61c50468441

**Comment by sils** [comment]
ack https://github.com/coala/documentation/pull/413/commits/a6d02ccfd30446645e646f46b8af87222830813b

**Comment by sils** [comment]
ack https://github.com/coala/documentation/pull/413/commits/bfa74dcd0bba647508c48090f169c71e4bcc1946 https://github.com/coala/documentation/pull/413/commits/c86216dfacf37b5ada08f172a7f5bfc1e5b49fd3

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
