### PR TITLE
FAQ.rst: Add question "What is a bear anyway?"

### PR DESCRIPTION
**Pull request by sarthakchakerverty**
This adds a brief description on what a bear is.

Closes https://github.com/coala/documentation/issues/284

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by sarthakchakerverty** [comment]
@MacBox7 Yes I already know that, please let me work and dont do weird reviews.Thanks

**Comment by yzgyyang** [comment]
> please let me work and dont do weird reviews

If it's a WIP, add and remove tags accordingly so the reviewers don't get confused.

**Comment by pareksha** [comment]
You can also write [WIP] at the start of your commit shortlog to indicate the work is in progress and not ready to be reviewed yet.

**Comment by sarthakchakerverty** [comment]
@pareksha Thanks for reviewing.Changing its position.

**Comment by sarthakchakerverty** [comment]
@jayvdb This issue is all set set up for review,please check if any changes are required.

**Comment by sarthakchakerverty** [comment]
@yzgyyang i deleted that .coafile because that wasn't a part of the master branch,but was created when I ran coala on my local computer.

**Comment by yzgyyang** [comment]
>  i deleted that .coafile because that wasn't a part of the master branch,but was created when I ran coala on my local computer.

As the diff of this PR is between `coala:master` and `sarthakchakerverty:faq_add_QnA`, it appears that you deleted the file in `master`.

In fact, the file is in `master`. https://github.com/coala/documentation/blob/master/.coafile

**Comment by sarthakchakerverty** [comment]
@yzgyyang Oh,I am sorry,I do admit my mistake.
Can you please suggest me a way out of this isssue?

**Comment by yzgyyang** [comment]
> Can you please suggest me a way out of this isssue?

Reset your last commit, correct the error, then redo the commit. Check out ohshitgit.com mentioned in the doc if you want to learn more git recovery tips.

**Comment by sarthakchakerverty** [comment]
On it.Thanks @yzgyyang

**Comment by yzgyyang** [comment]
@sarthakchakerverty  You don't have to delete the branch. Just reset your last commit.

**Pull request closed without merging**
