### PR TITLE
Added note for ubuntu users

### PR DESCRIPTION
**Pull request by vaishnavm217**
Mentioned the warning for not installing the wrong package using apt command
fixes https://github.com/coala/documentation/issues/392

### CODE REVIEW

**Comment by sims1253** [comment]
You still have comments from Gitmate on your PR. Please fix them :)

Please squash your commits into one using the `git rebase -i` command. 
Also please follow the newcomer guide and read http://coala.io/commits and rework your commit message accordingly.
You can change an existing commit (including it's message) with `git commit --amend`
and finally you have to push again with `git push -f` overwriting the old commits in the repo.

**Comment by sims1253** [comment]
Also this is not a bug fix so please use Closes in your commit message.
The newcomer guide should offer all the necessary steps.

**Comment by supergr35** [comment]
Marking WIP because of gitmate issues.

**Comment by supergr35** [comment]
It seems like you might want to squash these 4 commits into 1 commit, here's the directions as to how you would do that 😄 
http://api.coala.io/en/latest/Developers/Git_Basics.html#squashing-your-commits

**Pull request closed without merging**
