### PR TITLE
Replaced coala-analyzer to coala 

### PR DESCRIPTION
**Pull request by akashfoss**
This patch includes all the changes in Developers/Newcomers_Guide.rst

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
hey, this PR is kind of a mess, please follow this rebasing tutorial as it may fix it:


Hi,

it looks like your PR is out of date and needs a rebase. [This page](http://coala.io/git) may help you to get started on this. (*Do not press the update branch button. It's evil.*)

We also have a quick video tutorial on how to rebase: [https://asciinema.org/a/78683](https://asciinema.org/a/78683). That should help you understand the basics of how it works and what you should be doing.

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

(Be sure to use the coala-bears URL if you're on coala bears!)

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix it up for you - just tell us :).

Ping us on [our gitter channel](https://coala.io/chat) if you need help!

**Comment by aptrishu** [comment]
Still on this ? @akashfoss

**Comment by akashfoss** [comment]
Hey aptrishu, 
I was stuck in submitting the PR properly, if you want to work on it then please go for it :+1:

**Comment by aptrishu** [comment]
Ask for help on our [gitter channel](https://gitter.im/coala/coala). Someone will help you get your PR right.

**Comment by sils** [comment]
hey please squash together your commits, we can't review them properly if they're in this shape. We're here to help you on the chat and in the comments. There's also google with loads of tutorials (please consult those first before asking).

**Comment by sils** [comment]
it seems even that this PR doesn't change a thing :P

**Comment by akashfoss** [comment]
Yeah, I just changed all the things as they were earlier. I feel to edit it once more and make this PR readable. Thanks sils :+1:

**Comment by adtac** [comment]
@akashfoss this is still a bit of a mess - there are currently 7 commits. Could you squash them into one? Also please follow out commit guidelines for that. Marking as WIP till then since it's currently unreviewable.

**Comment by akashfoss** [comment]
I have squashed almost 7 commits, the last commit is unable to squash. Is this PR looking good now?

**Comment by srisankethu** [comment]
@akashfoss Looks like you brought it down to a single commit :+1:  Follow [this](http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html) guide to correct your commit message. Use ``--amend`` flag to amend your commit message.

**Comment by AbdealiJK** [comment]
Quick update here: Rebase needed and commit guidelines has not been met.
Don't add the Fixes statement if it is not fixing an issue.
       70

**Comment by akashfoss** [comment]
@AbdealiJK I have changed the commit according to the commit guide. Hope now it is looking good and readable.

**Comment by srisankethu** [comment]
@akashfoss Looks good. Rebase needed :+1:

**Comment by sils** [comment]
- Closes note missing
- There's a conflict, rebase needed

**Comment by Adrianzatreanu** [comment]
Yes, please fix the git conflict as we cannot merge it like this :( 
ask on gitter if you need help!

**Comment by akashfoss** [comment]
Rebased. Is it okay now?

**Comment by aptrishu** [comment]
1 - I don't think You have rebased, You see the conflicting files there ?
2 - Closes/Fixes note at the end of commit message is missing. Please go through https://coala.io/commit

**Comment by jayvdb** [comment]
GitHub still says "This branch has conflicts that must be resolved".

**Comment by adtac** [comment]
@akashfoss the best way to see how far behind or ahead you are graphically is to go to your branch (https://github.com/akashfoss/documentation). You'll find something like "This branch is 1 commit ahead, 53 commits behind coala:master."

**Comment by akashfoss** [comment]
So, should I rebase all other commits too? I mean the commits by other authors too?

**Comment by Nosferatul** [comment]
yes, you need to have only commits ahead. no commits behind are allowed when you want to merge

**Comment by akashfoss** [comment]
Hey, can anyone help me with this? I am stuck in the rebase part, though I rebased all the previous commit too.

**Pull request closed without merging**
