### PR TITLE
Newcomers_Guide.rst: Fix the broken link to Writing Bears guide

### PR DESCRIPTION
**Pull request by yash-nisar**
Closes https://github.com/coala/documentation/issues/98

### CODE REVIEW

**Comment by yash-nisar** [comment]
Please review @Adrianzatreanu

**Comment by srisankethu** [comment]
Change from the commit message from `Closes link` to `Fixes link` since broken links are considered as bugs.

**Comment by yash-nisar** [comment]
Sure, thanks !

**Comment by Adrianzatreanu** [comment]
also, shortlog has 63 chars, maximum is allow is 50, please cut a few and write a better one, thanks :D

**Comment by yash-nisar** [comment]
Is this good @Adrianzatreanu ?

**Comment by Adrianzatreanu** [comment]
yes, cool :D

ack e4f86fb

**Comment by Adrianzatreanu** [comment]
ack e3f86fb

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
