### PR TITLE
Writing Good Commits: missing blank lines 

### PR DESCRIPTION
**Pull request by charlesBak**

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
hey, this PR is quite a mess:
 - it has a merge commit - can be fixed by rebasing, type cobot explain rebase on the main gitter channel

 - has duplicate commits - can be fixed by rebasing interactively with "git rebase -i origin" and squashing some commits

- has commit message not according to our guidelines: Please read this small guide coala.io/commit to learn our guidelynes

**Comment by Adrianzatreanu** [comment]
we are always there on coala.io/chat (gitter channel) if you need any kind of help!

**Comment by charlesBak** [comment]
hey @Adrianzatreanu can you give me an example of commit for this issue for example: 	https://github.com/coala/documentation/issues/254

**Comment by Adrianzatreanu** [comment]
``MAC_Hints: Change OSX and MAC to macOS``

``Closes https://github.com/coala/documentation/issues/254``

**Comment by Adrianzatreanu** [comment]
yes, after the shortlog, separated by a newline

**Comment by Adrianzatreanu** [comment]
closing due to high inactivity

**Pull request closed without merging**
