### PR TITLE
Glob_Patterns.rst: Modify the examples

### PR DESCRIPTION
**Pull request by aptrishu**
It removes some examples and fixes a typo.

Fixes https://github.com/coala/documentation/issues/70

### CODE REVIEW

**Comment by Asnelchristian** [comment]
can you remove some of the examples in one commit and correct the docs in another one

**Comment by aptrishu** [comment]
Yes sure. So, for that first I should revert all the changes ? then do all that again ?

**Comment by aptrishu** [comment]
It was a single simple typo. I though it's not worth a whole commit.

**Comment by Makman2** [comment]
if the changes are not too complex, you can do `git revert HEAD~1` which resets you one commit back and keeps your changes as unstaged. Then you can readd them with `git add -p` selecting the relevant parts.

What I usually do is using interactive rebase: Make a commit that introduces the old state again for the particular change, make a revert commit for that, fixing up the old-state-again-commit with the the very first commit and changing the message of the revert commit to "Fixed this particular thing (whatever)"

your choice :3 there are probably other methods as well, I think resetting and readding is probably the easiest in this case :P

**Comment by sils** [comment]
not revert, reset!

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by Makman2** [comment]
Ahh my bad, changed :3

**Pull request closed without merging**
