### PR TITLE
FAQ.rst: Adds reference to list of exit codes

### LINKED ISSUE #442: FAQ: "Can I Use coala in my Continuous Integration?" - Include exit-codes link
Currently it states:
> Yes! There’s an argument –ci that runs the coala binary in non-interactive mode, which shows results cleanly in the log and returns error codes if something goes wrong.

We should link to the exit code page so someone can immediately find it. Especially googling "coala exit codes" has given me the FAQ as a first hit.

The exit codes can be found in `Users/Exit_Codes.rst` in this repo and the webpage is currently residing here on our website: https://docs.coala.io/en/latest/Users/Exit_Codes.html

### PR DESCRIPTION
**Pull request by AnishHota**
Fixes #442.Added link to a list of exit codes and their meanings.

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by AnishHota** [comment]
@gitmate-bot what should i update ?

**Comment by shreyans800755** [comment]
@AnishHota 
Can you please remove Merge commit ? 

Keep commit message something like:

> FAQ.rst: Add exit codes reference

> Adds exit codes reference documentation's reference
in Help/FAQ.rst.

> Fixes https://github.com/coala/documentation/issues/442

And regarding
> @gitmate-bot what should i update ?
Gitmate just gives you remainder after certain time periodically. You should act if you need rebase or status is WIP.

**Comment by shreyans800755** [comment]
unack c81f631

**Comment by AnishHota** [comment]
@shreyans800755 I did as you instructed. What should i do next?

**Comment by shreyans800755** [comment]
@AnishHota 
You haven't really followed as per my comment. You have to refer the issue in the commit message and not use past tense. Keep message something like this:
Shortlog:

> `FAQ.rst: Add reference to list of exit codes`

Body:

> `Fixes #442`

 Please try to follow instructions given at coala.io/commit.

**Comment by AnishHota** [comment]
@shreyans800755 Sorry,my bad. Rectified it. Is it okay now or should i change anything else?

**Comment by shreyans800755** [comment]
ack 785f1de

**Comment by rhemon** [comment]
wouldn't the commit message be better if its something like 'Adds link to exit codes' documentation in Help/FAQ.rst.' ? since the repetition of "reference" makes it kind of seem confusing to me. could also be "reference" instead of "link"

**Comment by AnishHota** [comment]
@rhemon You are right.It is a little bit confusing.I am changing the commit message.

**Comment by mridubhatnagar** [comment]
@shreyans800755 yes the changes seem to be good. But, @AnishHota you have resolved this issue on your master branch itself. In your forked repo the branch name is AnishHota:master. 
For understanding git-basics you can go through the document http://api.coala.io/en/latest/Developers/Git_Basics.html.

To start working on a new issue you must create a branch.

```
git checkout -b branchname
```

**Comment by AnishHota** [comment]
@mridubhatnagar Yeah, i know i should have made a branch, made the changes there and sent a pr from the branch.It's just that this is my first pr, i didn't knew it back then.But after this , i did learn the basics, and my other prs were merged.Thank you.

**Comment by mridubhatnagar** [comment]
@AnishHota Thanks. That's absolutely alright.

**Comment by AnishHota** [comment]
@mridubhatnagar The problem is i cant contribute anymore unless this pr is merged. Is there any way to contribute?

**Comment by Arsfiqball** [comment]
Please rebase @AnishHota

**Comment by AnishHota** [comment]
@Arsfiqball Sorry,i am not sure what you mean.But i rebased it with upstream/master.Is that it?

**Comment by shreyans800755** [comment]
@AnishHota That is good enough.

**Comment by shreyans800755** [comment]
ack 43c9d82

**Comment by AnishHota** [comment]
@rultor What can i do?

**Comment by AnishHota** [comment]
@jayvdb What should i do?

**Comment by AnishHota** [comment]
@shreyans800755 @mridubhatnagar Any idea what's wrong? Help needed.

**Comment by adtac** [comment]
ack https://github.com/coala/documentation/pull/443/commits/43c9d82a5c8a41232bed6daf88569f4abfcae859

**Comment by adtac** [comment]
@rultor merge

**Pull request merged**
